name: Publish Docker image
on:
  push:
  schedule:
    - cron: "40 21 1 * *"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: [[68, esr68], [78, esr78], [91, esr91], [91, release]]
        base:
          [
            [ek874-108, "anyakichi/yocto-rzg2-builder:ek874-108"],
            [hihope-rzg2h-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-108"],
            [hihope-rzg2m-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-108"],
            [hihope-rzg2n-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-108"],
            [smarc-rzg2l-13, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-13"],
            [smarc-rzg2lc-13, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-13"],
            [smarc-rzg2l-13u1, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-13u1"],
            [smarc-rzg2lc-13u1, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-13u1"],
            [smarc-rzg2l-13u2, "anyakichi/yocto-rzg2-builder:smarc-rzg2l-13u2"],
            [smarc-rzg2lc-13u2, "anyakichi/yocto-rzg2-builder:smarc-rzg2lc-13u2"],
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/gecko-embedded-builder
            ghcr.io/anyakichi/gecko-embedded-builder
          tags: ${{ matrix.base[0] }}-${{ matrix.firefox[1] }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            builder_base=${{ matrix.base[1] }}
            firefox_version=${{ matrix.firefox[0] }}
            subdir=${{ matrix.firefox[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_and_push_esr60:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          [
            [ek874-108, "anyakichi/yocto-rzg2-builder:ek874-108"],
            [hihope-rzg2h-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2h-108"],
            [hihope-rzg2m-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2m-108"],
            [hihope-rzg2n-108, "anyakichi/yocto-rzg2-builder:hihope-rzg2n-108"],
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/gecko-embedded-builder
            ghcr.io/anyakichi/gecko-embedded-builder
          tags: ${{ matrix.base[0] }}-esr60
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.esr60
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            builder_base=${{ matrix.base[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
